function R = peri2geo(OMEGA, omega, i)
% perifocal coordinate frame transform into geocentric coordinate frame 
R = [...
    (cos(OMEGA)*cos(omega) - sin(OMEGA)*sin(omega)*sin(i)), -cos(OMEGA)*sin(omega) - sin(OMEGA)*cos(omega)*cos(i), sin(OMEGA)*sin(i);...
    (cos(OMEGA)*cos(omega) + sin(OMEGA)*sin(omega)*sin(i)), -cos(OMEGA)*sin(omega) + sin(OMEGA)*cos(omega)*cos(i), -cos(OMEGA)*cos(i);...
    sin(omega)*sin(i), cos(omega)*sin(i), cos(i)...
    ];
end


