function R = peri2geo(OMEGA, omega, i)
% perifocal coordinate frame transform into geocentric coordinate frame 
R = [...
    (cosd(OMEGA)*cosd(omega) - sind(OMEGA)*sind(omega)*cosd(i)), -cosd(OMEGA)*sind(omega) - sind(OMEGA)*cos(omega)*cosd(i), sind(OMEGA)*sind(i);...
    (sind(OMEGA)*cosd(omega) + cosd(OMEGA)*sind(omega)*cosd(i)), -sind(OMEGA)*sind(omega) + cosd(OMEGA)*cosd(omega)*cosd(i), -cosd(OMEGA)*sind(i);...
    sind(omega)*sind(i), cosd(omega)*sind(i), cosd(i)...
    ];
end


