function D = topo2geo(L, theta) 
% theta is also called 'sidereal'
% topocentric-horizon coordinate frame transform into geocentric coordinate
% frame
D = [...
    sin(L)*cos(theta), sin(L)*sin(theta), -cos(L);...
    -sin(theta), cos(theta), 0;...
    cos(L)*cos(theta), cos(L)*sin(theta), sin(L)...
    ];
end
