function D = topo2geo(L, theta) 
% theta is also called 'sidereal'
% topocentric-horizon coordinate frame transform into geocentric coordinate
% frame
D = [...
    sind(L)*cosd(theta), sind(L)*sind(theta), -cosd(L);...
    -sind(theta), cosd(theta), 0;...
    cosd(L)*cosd(theta), cosd(L)*sind(theta), sind(L)...
    ];
end
